### ISSUE TITLE
Add remaining API endpoints

### ISSUE THREAD

**Issue by SpaceManiac** [SpaceManiac/discord-rs#1]
- [x] post message with attachment
- [x] get bans
- [x] add ban
- [x] remove ban
- [x] create invite
- [x] ~~get member list~~
- [x] get member
- [x] edit member
- [x] kick member
- [x] create role
- [x] edit role
- [x] reorder roles
- [x] delete roles
- [x] create role permission
- [x] delete permission
- [x] edit profile
- [x] get voice regions
- [x] move member voice
- [x] get servers
- [x] edit server

**Comment by brandon515** [comment]
#96 Adds the rest of the endpoints
