### ISSUE TITLE
Mark Event::__Nonexhaustive as unstable

### ISSUE THREAD

**Issue by oberien** [SpaceManiac/discord-rs#101]
Mark [`Event::__Nonexhaustive`](https://github.com/SpaceManiac/discord-rs/blob/v0.7.0/src/model.rs#L1891-L1893) as unstable to prevent matching against it in stable code. This is also done in [`std::io::Error`](https://github.com/rust-lang/rust/blob/241a9d0ddf99fd40d273c615e9b1e8ce6052d94a/src/libstd/io/error.rs#L163-L166).

**Comment by clarfonthey** [comment]
This doesn't work outside of rustc; you just mark it as `#[doc(hidden)]` and that's all you can do.

**Comment by oberien** [comment]
Wasn't aware of that. Thanks for the clarification.
