### ISSUE TITLE
Incorrect LiveServer::members_count and LiveServer::members vector

### ISSUE THREAD

**Issue by iddm** [SpaceManiac/discord-rs#105]
I have 2 users on the server.

When I invite 3rd and he comes, the following code is executed:          

```rust
  Event::ServerMemberAdd(server_id, member) => {
                if let Some(s) = self.state.servers().iter().find(|srv| srv.id == server_id) {
                info!("New user joined the server({}): {:?}", s.name, member.user);
                    self.messenger().send_message(s.channels[0].id,
                                                  &format!("Everyone say hello to {}, our new member! We are {} already!",
                                                          member.user.id.mention(),
                                                          markdown::bold(&s.member_count.to_string())),
                                                  false);
                info!("Users are: {:?}", s.members);
                }
```
However, when the new user comes it prints `We are 4 already` while it should be 3 users only. 
So I decided to look `s.members` (what is `LiveServer::members`): 

`[2017-03-28][17:09:41.065212848][INFO] in (discord_pickupbot::pickupbot::bot) at src/pickupbot/bot.rs:796 Users are: [Member { user: User { id: UserId(183254040266670080), name: "PAPA_LOX", discriminator: 7986, avatar: Some("633012bc9cdd1dda5e5ae83a74e3ef90"), bot: false }, roles: [RoleId(246283517795762176)], nick: None, joined_at: "2016-09-24T11:18:36.863000+00:00", mute: false, deaf: false }, Member { user: User { id: UserId(184244497650024448), name: "pickupbottester", discriminator: 8476, avatar: Some("63d00ee0e74973ca8fefad5a5494b35b"), bot: true }, roles: [RoleId(229551034421346304)], nick: None, joined_at: "2016-09-24T16:58:42.060000+00:00", mute: false, deaf: false }, Member { user: User { id: UserId(138948472849170432), name: "Danmer", discriminator: 4805, avatar: Some("d84f4c80cdbf3fdbecbb3a9b3c0aeae3"), bot: false }, roles: [], nick: None, joined_at: "2017-03-28T14:09:40.791304+00:00", mute: false, deaf: false }, Member { user: User { id: UserId(138948472849170432), name: "Danmer", discriminator: 4805, avatar: Some("d84f4c80cdbf3fdbecbb3a9b3c0aeae3"), bot: false }, roles: [], nick: None, joined_at: "2017-03-28T14:09:40.791304+00:00", mute: false, deaf: false }]`

The new user's name is `Danmer`. Why is he listed twice?

P.S. I have also been able to reproduce the error on another server where 400+ members are: each new user increments `members_count` by 2 instead of 1.

**Comment by SpaceManiac** [comment]
I *believe* this was resolved in chat as having to do with calling `State::update` twice, please comment back iff this is not the case.

**Comment by pheki** [comment]
Hey, I think I'm also having this issue with a bot... I'm testing in a server with just me and the bot, and if I'm in a voice channel when the bot CONNECTS, I appear as Member twice, otherwise I just don't appear...

Code to reproduce:

```rust
// Missing use statements here

fn main() {
    // Get token somehow
    // ...

    let discord = Arc::new(Discord::from_bot_token(token).expect("login failed"));

    // Establish and use a websocket connection
    let (connection, ready_event) = discord.connect().expect("could not connect to discord");

    info!("Discord connection succesfull");

    thread::spawn({
        let discord = discord.clone();
        move || discord_event_loop(discord, connection, ready_event)
    });

    // Unrelated
    loop {
        thread::sleep(std::time::Duration::from_secs(200));
    }
}

fn discord_event_loop(discord: Arc<Discord>, mut connection: discord::Connection, ready_event: ReadyEvent) {
    let mut state = State::new(ready_event);
    // This actually doesn't make a difference
    connection.sync_calls(&state.all_private_channels());

    for server in state.servers() {
        // Doesn't actually print anything
        info!("Initial Members: {:?}", server.members);
    }
    loop {
        let event = match connection.recv_event() {
            Ok(event) => event,
            Err(err) => {
                warn!("Discord api received error: {:?}", err);
                if let discord::Error::WebSocket(..) = err {
                    // Handle the websocket connection being dropped
                    let (new_connection, ready) = discord.connect().expect("connect failed");
                    connection = new_connection;
                    state = State::new(ready);
                    info!("Discord api reconnected successfully.");
                }
                if let discord::Error::Closed(code, body) = err {
                    error!("Gateway closed on us with code {:?}: {}", code, body);
                    break;
                }
                continue;
            }
        };
        state.update(&event);

        match event {
            Event::MessageCreate(message) => {
                for server in state.servers() {
                    info!("Members: {:?}", server.members);
                }
            }
            _ => {}
        }
    }
}
```

Will print (if I'm not connected to voice chat):
```
 INFO > Discord connection succesfull
// then I send any message on #general
 INFO > Members: [Member { redacted_bot_info }]
```

Will print (if I'm connected to voice chat):
```
 INFO > Discord connection succesfull
// then I send any message on #general
 INFO > Members: [Member { my_redacted_info }, Member { my_redacted_info }, Member { redacted_bot_info }]
```

My bot's permissions are:
- View channels (Read Text Channels & See Voice Channels)
- Send messages
- Mute members
- Deafen members
