### ISSUE TITLE
Errors when connecting to Discord

### ISSUE THREAD

**Issue by CryZe** [SpaceManiac/discord-rs#11]
Apparently it can't decode the LiveServer at all and says that all of the keys (at least name and owner_id, but I presume most others, if not all, as well) are absent.

Update: Apparently a Live Server can also have this format:

``` json
{"id":"169421923531358208","unavailable":true}
```

Looks like this is a duplicate of #8

**Comment by SpaceManiac** [comment]
A recent commit fixed this. You should be able to continue by using the git version of discord-rs rather than 0.5.0, for example by using this line in the `[dependencies]` section of your Cargo.toml:

``` toml
discord = { git = "https://github.com/SpaceManiac/discord-rs" }
```

**Comment by CryZe** [comment]
Yeah, I noticed that. It works now :)
Really cool library btw ^^
