### ISSUE TITLE
Easier JSON encoding?

### ISSUE THREAD

**Issue by jD91mZM2** [SpaceManiac/discord-rs#112]
Any possibility you could implement the Serializable interface in all the models:: things? I want to encode a guild to JSON, but right now I have to write every single key with every single value... It's a pain.

**Comment by SpaceManiac** [comment]
I may move to using `serde_derive` to generate deserialization code, which would mean I could easily implement `Serializable` on the model structs. Of note though is that this would mean the serialized forms will match more closely the Discord representation than the Rust one. Hopefully this is sufficient for your use case.

**Comment by jD91mZM2** [comment]
That's *exactly* what I want :stuck_out_tongue:   
I like low-level :smile:

**Comment by SpaceManiac** [comment]
Check out the recent commits for a starting point. The most complex structs are yet to be transitioned, but all of the simple data types now implement `Serialize`/`Deserialize`.

**Comment by jD91mZM2** [comment]
:+1:

**Comment by jD91mZM2** [comment]
Similar to this, but could we also get deserialization for builders? :stuck_out_tongue:

Thanks! Wonderful work, by the way!

**Comment by SpaceManiac** [comment]
Which builders are most important to you? It's fairly easy to offer the basic functionality, but there are some caveats in particular with EditServer, EditProfile, and EditUserProfile where the current data must also be included in the object for the request to be valid. Right now the library fills that in for you before allowing access to the builder, but that will be lost if you drop the builder and deserialize one.

**Comment by jD91mZM2** [comment]
All the embed builders would be really cool if I could create from user input :)

**Comment by jD91mZM2** [comment]
I guess I should close this :thinking:
