### ISSUE TITLE
Consider making connection's shutdown() take a reference

### ISSUE THREAD

**Issue by jD91mZM2** [SpaceManiac/discord-rs#116]
~~Don't get me wrong, taking `mut self` definitely the ideal approach. However, it sadly comes with a price. It assumes you own the instance, and therefor cannot be used easily in functions. Especially since the lack of Clone (which is a good thing. You cannot clone a connection - that'd just be misleading and weird).~~
I am stupid, I didn't know about `mem::replace`.

So, do consider changing it to take a `&mut self`. Maybe even implement the drop trait :+1:

**Comment by Xaeroxe** [comment]
You can create functions that consume values, so you can still use this in a function.  If you have a function that optionally consumes a value you might want to rethink your program design.

**Comment by jD91mZM2** [comment]
I do it based on user input. So it's not really too bad program design.

**Comment by Xaeroxe** [comment]
@legolord208 This is my best attempt at optional consumption.  It's not the prettiest program design but eh it works.

https://play.rust-lang.org/?gist=eabd2bf88686f5e4d614d704c4762821&version=stable&backtrace=0

**Comment by jD91mZM2** [comment]
Excuse me - how's the relevance if that? It'd been one thing if it was the same string and you called .into_bytes based on some other string, but...?

**Comment by Xaeroxe** [comment]
It's optional consumption.  If food isn't consumed (You didn't choose to shutdown discord) then the string is given back.  If it is consumed (You chose to shut down discord) then the value isn't returned instead you get None.  String is an owned value so if you don't return string at the end of the function then food will be destroyed.

**Comment by Xaeroxe** [comment]
Basically it's your workaround.  This will let you pass in a connection to a function, if the connection isn't closed in the function then you can continue using it in later statements.

**Comment by Xaeroxe** [comment]
```Rust
fn cookie_monster(food: String) -> Option<String> {
    if food == "cookie" {
        println!("Nom nom nom");
        food.into_bytes();
        None
    } else {
        println!("Eww");
        Some(food)
    }
}
```

There, this version is a little more explicit about the consumption.  Still works the same though.

**Comment by jD91mZM2** [comment]
Okay, that is a good workaround. Not as clean as I would like it, but it works.

**Comment by jD91mZM2** [comment]
On the other hand, that causes issues with `move` closures.

I generally think implementing the `drop` trait would be nice anyways. Imagine how awesome it would be having it clean up on itself without having to worry about it?

**Comment by jD91mZM2** [comment]
I like the way [tempdir](https://github.com/rust-lang-nursery/tempdir) did it. They have two functions. One that does cleanup, and the drop trait which also does cleanup, in case it hasn't already been ran.

This allows optionally seeing the error message, but also always cleaning up.

**Comment by SpaceManiac** [comment]
I want to say there was rationale for not implementing `Drop`, but I don't remember what it is, so that will probably be the solution.

**Comment by SpaceManiac** [comment]
`Connection` now implements `Drop`. If this works out in practice, I'll close this.

**Comment by jD91mZM2** [comment]
Woo! I can't really test it, but it sounds amazing!
