### ISSUE TITLE
Any chance to get recv_event to take an immutable reference?

### ISSUE THREAD

**Issue by jD91mZM2** [SpaceManiac/discord-rs#118]
[See this question and comment.](https://www.reddit.com/r/rust/comments/6e6nwu/accessing_event_loop_via_mutex/diba5c4/)

Apparently it's near impossible to use recv_event concurrently, with for example user input. Any chance to make it take an immutable reference, or is this a problem with an upstream repository?

**Comment by anna-is-cute** [comment]
See also/possible duplicate of #109

**Comment by jD91mZM2** [comment]
Yeah, that's a duplicate. Thanks for the heads up :)
