### ISSUE TITLE
Implement FromStr

### ISSUE THREAD

**Issue by jD91mZM2** [SpaceManiac/discord-rs#125]
Hey! You implemented from_str on OnlineStatus et.c... but you never actually implemented the trait FromStr. We can't actually write `string.parse::<OnlineStatus>()`.

**Comment by Tormyst** [comment]
Perhaps I am missing something, but from_str is not implemented.  from_name is implemented through the serial_names! macro.  It's basically the same idea.  I opened a pull request: #126, but please let me know if I am wrong about this functions existence.  

I am only now getting my hands dirty in Macros, and it is a shame that there is no decorator system on macros.  That would have improved this implementation.

**Comment by jD91mZM2** [comment]
![image](https://user-images.githubusercontent.com/12830969/27805458-1f90e3e8-6035-11e7-8c09-9745fe64c1bb.png)

[Here is from_str in the docs](https://docs.rs/discord/0.8.0/discord/model/enum.OnlineStatus.html#method.from_str). However, since the docs follow the latest cargo version and not the latest git, they could be outdated.

**Comment by Tormyst** [comment]
Generating the latest documentation, it is indeed no longer there.  Instread it looks like that function was just renamed to from_name as it has the same signature.  
That might also be for the best as FromStr requires a different type anyway.  It expects a Result rather then an Option.  
```rust
    type Err;
    fn from_str(s: &str) -> Result<Self, Self::Err>;
```

**Comment by Xaeroxe** [comment]
I mean `Err(())` is a thing.

**Comment by Tormyst** [comment]
While `Option<T>` and `Result<T,()>` are more or less the same, there is no auto convert between those types to the best of my knowledge, and `.ok_or()` is probably the easiest convert operation.  In addition, the library uses a replacement result type of `Result<T,error::Error>`, it probably makes sense to continue using `error::Error` as the error type in this case.
If not, I will gladly update my pull.

**Comment by jD91mZM2** [comment]
You are right. I didn't know it was changed, and that's why I thought it didn't make sense to not implement FromStr.
