### ISSUE TITLE
Fails to build with `expected identifier, found keyword "self"`

### ISSUE THREAD

**Issue by ToxicFrog** [SpaceManiac/discord-rs#127]
Using rust 1.15.1, it fails to compile with four errors of the form:

```
error: expected identifier, found keyword `self`
  --> /home/ben/.cargo/git/checkouts/discord-rs-e20ed8881d23c413/389f080/src/serial.rs:53:5
   |
53 |            ($self:ident, $v:ident, $wrong:expr) => {
   |              ^^^^
```

This happens both with master (shown) and 0.8.0.

**Comment by SpaceManiac** [comment]
Looks like this is only legal code in Rust 1.17+. Is there a particular reason you are on the older compiler?

**Comment by ToxicFrog** [comment]
That's what I got when I installed `rustc`. I tried it with `rustc-nightly` and it still failed, but looking at that it looks like `rustc-nightly` is 1.16.0 here (?!) so I think something has gone wrong with my distro's package management.

A note in the README that it needs Rust 1.17+ would be appreciated.

**Comment by Xaeroxe** [comment]
My verbiage for this would be:

We only support the latest stable compiler.  Use older versions, the beta channel, or the nightly channel at your own risk if you depend on this crate.

**Comment by SpaceManiac** [comment]
Formal minimum version on hold pending a good way to ensure compliance without leaning on CI. In the meantime, policy is "latest stable".
