### ISSUE TITLE
discord.connect() always fails

### ISSUE THREAD

**Issue by YaLTeR** [SpaceManiac/discord-rs#13]
`Decode("Expected string", null)`
Looks like this is coming from https://github.com/SpaceManiac/discord-rs/blob/master/src/connection.rs#L54

**Comment by chrisduerr** [comment]
Are you using the latest git version?

**Comment by YaLTeR** [comment]
Yep.

**Comment by SpaceManiac** [comment]
Thanks for the report, could you update and try again? I suspect 7b7516059cda8633f1e7e7076150178ff420cc69 will fix the issue.

**Comment by taiyaeix** [comment]
I was just having the same issue as well, 7b75160 has fixed it for me.

**Comment by YaLTeR** [comment]
Yep, fixed on 7b75160.
