### ISSUE TITLE
Don't use both `time` and `chrono`.

### ISSUE THREAD

**Issue by jD91mZM2** [SpaceManiac/discord-rs#130]
You're using both the `time` library, and the `chrono` library. Don't use both, please.

**Comment by SpaceManiac** [comment]
`time` is included transitively widely, so it's a little unclean but not going to be a major improvement to fix. If it's important to you I would accept a PR.
```
time v0.1.37
├── chrono v0.4.0
│   └── discord v0.8.0
├── cookie v0.2.5
│   └── hyper v0.9.18
│       ├── discord v0.8.0 (*)
│       ├── multipart v0.8.1
│       │   └── discord v0.8.0 (*)
│       └── websocket v0.17.1
│           └── discord v0.8.0 (*)
├── discord v0.8.0 (*)
└── hyper v0.9.18 (*)
```

**Comment by jD91mZM2** [comment]
Not important, but I'll definitely consider it :smile:.
Thanks for the reply!

**Comment by SpaceManiac** [comment]
c52c75a77a60167df1e39a21bc2a155f8d97dc14
