### ISSUE TITLE
RustFmt?

### ISSUE THREAD

**Issue by jD91mZM2** [SpaceManiac/discord-rs#138]
Hey! Is there any chance to get some official RustFmt config here? It's very configurable, so it should be able to look however you want it to.

It's a little annoying having to disable auto formatting on save every time I make a pull request, haha

**Comment by SpaceManiac** [comment]
A barebones `rustfmt.toml` was added in c5f4c36b09b9eb6e1dcd66d79fc8851ad71f4e03.
