### ISSUE TITLE
Err returned from recv_event() when bot profile is updated

### ISSUE THREAD

**Issue by bdonlan** [SpaceManiac/discord-rs#139]
## Overview

When a bot profile is updated using the developer application profile page, discord sends a `USER_UPDATE` event that is missing expected fields, resulting in a serialization error being returned from `recv_event()`.

## Reproduction steps

1. Establish a Connection using a bot token, and run `conn.recv_event().unwrap()` in a loop.
2. Go to https://discordapp.com/developers/applications/me, open the profile page for the bot, and edit its description.
3. Upon clicking save, you will see a panic like:

```
thread 'Discord poller' panicked at 'called `Result::unwrap()` on an `Err` value: Json(ErrorImpl { code: Message("missing field `verified`"), line: 0, column: 0 })', /checkout/src/libcore/result.rs:860
```

## Additional details

A sample update event loops like:

     Object({"d": Object({"avatar": Null, "bot": Bool(true), "discriminator": String("2591"), "id": String("338143926617767936"), "username": String("Meubot")}), "op": Number(PosInt(0)), "s": Number(PosInt(9)), "t": String("USER_UPDATE")})

Notably, the verified and mfa_enabled fields are missing.

**Comment by bdonlan** [comment]
Adding `Option` to the `verified` and `mfa_enabled` fields of `CurrentUser` would be a way to fix this, but this would be a breaking API change. Thoughts?

**Comment by SpaceManiac** [comment]
The `UserUpdate` event needs to be changed to be patch-like, with `Option` fields rather than just a `CurrentUser`. If READY and `get_current_user` still return everything, `CurrentUser` should not change.

Discord changes behavior often enough that breaking changes are expected.

**Comment by bdonlan** [comment]
I'll see about putting together a PR a bit later then.
