### ISSUE TITLE
open_ytdl_stream seems to only work with certain video urls.

### ISSUE THREAD

**Issue by aarroz** [SpaceManiac/discord-rs#140]
When I tried the dj.rs example, youtube-dl would only stream certain videos and mostly reject whatever urls I tried with it. It appears to be a youtube-dl problem with the library, but youtube-dl seems fine.

**Comment by aarroz** [comment]
From what I tested, it seems to error when streaming a url with advertisements.

**Comment by SpaceManiac** [comment]
Hey, can you first make sure that `youtube-dl` is up to date (`youtube-dl --version` should be within the past few days), make sure it works in `youtube-dl` and not in the DJ example, and then link the video in question? I have been unable to reproduce.

**Comment by aarroz** [comment]
My youtube-dl version was from last year. Whoops. Seems to work now however.
