### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by jD91mZM2** [SpaceManiac/discord-rs#142]
~~I tried my best to update hyper version - but gave up.  
But I think updating hyper version would be cool, so if anybody wants to fix the last few things, you can use [my existing attempt](https://github.com/legolord208/discord-rs/tree/hyper).~~

EDIT: It seems easier to use [reqwest](https://crates.io/crates/reqwest). I have done some attempts myself this morning [here](https://github.com/legolord208/discord-rs/tree/reqwest).
Sadly we also have to update websocket and stuff because of openssl-sys, which seems kind of difficult.

**Comment by legolord208** [comment]
Update: Should we use [reqwest](https://docs.rs/reqwest/0.7.1/reqwest/) instead? It seems better at chaining and stuff

**Comment by jD91mZM2** [comment]
#143
