### ISSUE TITLE
Serialize UserId and ChannelId

### ISSUE THREAD

**Issue by keringar** [SpaceManiac/discord-rs#149]
Right now I'm using UserId and ChannelId in a config file to do permissions. However, they both don't implement Serialize and Deserialize so I have to do it myself.

**Comment by keringar** [comment]
Well I looked at the id! macro and it seems like it does derive Serialize and Deserialize. But its only in master for now. Any hints on when the next release will be?

**Comment by SpaceManiac** [comment]
Releases usually come after big changes in either Discord or the library, or when I feel like things are at a local minimum in terms of unaddressed issues. Discord itself changes too frequently to make frequent library releases (which will usually be breaking) sensible.
