### ISSUE TITLE
Simple example can't be compiled

### ISSUE THREAD

**Issue by iddm** [SpaceManiac/discord-rs#15]
When I try to compile the example from [here](https://github.com/SpaceManiac/discord-rs/blob/master/examples/basic_chatbot.rs) as it is I have a lot of errors:

```
main.rs:30:17: 30:51 error: no associated item named `Closed` found for type `discord::error::Error` in the current scope
main.rs:30             Err(discord::Error::Closed(code, body)) => {
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
main.rs:30:46: 30:50 error: the trait `core::marker::Sized` is not implemented for the type `[u8]` [E0277]
main.rs:30             Err(discord::Error::Closed(code, body)) => {
                                                        ^~~~
main.rs:30:46: 30:50 help: run `rustc --explain E0277` to see a detailed explanation
main.rs:30:46: 30:50 note: `[u8]` does not have a constant size known at compile-time
main.rs:30:46: 30:50 note: all local variables must have a statically known size
error: aborting due to 2 previous errors

```

Is there something wrong with the example code?

P.S. I am learning rust yet.

**Comment by iddm** [comment]
Checked the sources. I see everything is okay for the latest version but the main page of the project have a link to crate which says to use 0.5.0 version which has such problem.

This helps:

```
[dependencies]                   
discord = { git = "https://github.com/SpaceManiac/discord-rs", rev = "8a5fd83c" } 
```

However, I believe, maintainer should release 0.5.1 version.

**Comment by SpaceManiac** [comment]
The examples on the `master` branch track the library on the `master` branch. To access the examples as they were for `0.5.0`, visit here: https://github.com/SpaceManiac/discord-rs/tree/v0.5.0/examples

A next release will come soon. it is probably about time for one.
