### ISSUE TITLE
how to instantiate LiveServer struct

### ISSUE THREAD

**Issue by Ferryistaken** [SpaceManiac/discord-rs#163]
I'm trying to get how many members are in a given server and their id, but I couldn't find a way to instantiate `LiveServer`. The only thing that seemed like it in the [docs](https://wombat.platymuus.com/rustdoc/discord_master/model/struct.LiveServer.html) is the `decode` method, but when do I need to call that? Am I missing something? Maybe some documentation with explanations?

**Comment by SpaceManiac** [comment]
The [State::servers](https://wombat.platymuus.com/rustdoc/discord_master/struct.State.html#method.servers) method will return a list of LiveServers. See [this example](https://github.com/SpaceManiac/discord-rs/blob/150e6b469d0351d7d2d563183f4dd73b4eb31738/examples/logbot.rs#L13-L16).
