### ISSUE TITLE
README Discord invite link is invalid.

### ISSUE THREAD

**Issue by DomtronVox** [SpaceManiac/discord-rs#164]
You click on the discord badge in the readme and it takes you to an invalid invite. Had a question I was going to ask but cannot find the chat server.

`[![](https://img.shields.io/badge/chat-Discord-blue.svg)](https://discord.gg/0SBTUU1wZTWAPisK)`

**Comment by SpaceManiac** [comment]
Thanks for noticing. It's been invalid for two years or more by now. I've removed it. Questions can be asked here, but I can't promise any particular haste in replying.
