### ISSUE TITLE
there is a token altough it throws 'Expected token: NotPresent' error.

### ISSUE THREAD

**Issue by Akin-Selcuk** [SpaceManiac/discord-rs#175]
I just copied  the code from examples and settled up everything but it throws 'Expected token: NotPresent'. I tried ".unwrap()" to locate the issue but its the same issue. What I done wrong?

**Comment by SpaceManiac** [comment]
The examples contain `env::var("DISCORD_TOKEN").expect("Expected token")`.

In other words, they look for the `DISCORD_TOKEN` environment variable and use that.

If you want to retrieve the token from some other location, such as a file, modify the example.

**Comment by itschip** [comment]
You can run `export DISCORD_TOKEN=token` if you'd like.
