### ISSUE TITLE
Add Travis CI Support

### ISSUE THREAD

**Issue by indiv0** [SpaceManiac/discord-rs#35]
This is a tracking issue for adding Travis CI support to the project.

I'll probably be implementing this myself.

**Comment by ghost** [comment]
Unless you're actively working on this, I'm going to pick this up as part of another patch.

**Comment by indiv0** [comment]
I'm currently away on vacation, so feel free to work on it.

Once I get back, I can just submit a PR for anything that might be missing.

**Comment by SpaceManiac** [comment]
Closed by #133.
