### ISSUE TITLE
Group chats and calls updates

### ISSUE THREAD

**Issue by SpaceManiac** [SpaceManiac/discord-rs#42]
**Incomplete list** pending Discord's release of these features.
- PrivateChannel has `{"type":"text"}`
- PublicChannel has `{"is_private":false}` (only sometimes)
- Message has `{"type":0}`
  - Type 3 example: https://gist.github.com/Rapptz/9885d3318be589fd9cec7f57362b826b
- Event::MessageUpdate has `{"type":0}`

**Comment by ghost** [comment]
Can be closed now ✅
