### ISSUE TITLE
Logout unauthorized

### ISSUE THREAD

**Issue by tastytentacles** [SpaceManiac/discord-rs#62]
so when I try to call
`client.logout().expect("logout failed");`

I get this for some reason
`thread '<main>' panicked at 'logout failed: Status(Unauthorized, Some({"code":0,"message":"401: Unauthorized"}))', src/libcore/result.rs:785`

I am playing with one of the example projects but I changed the login to use `Discord::new_cache` so I could pass in my login details.

could this have broken it?

**Comment by SpaceManiac** [comment]
Just don't bother calling `.logout()`. I should probably just delete this method; even when it doesn't fail, it doesn't _do_ anything.
