### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by nabijaczleweli** [SpaceManiac/discord-rs#79]
The current HEAD contains some new features that would be rather nice to have (like `Discord::get_server_channels()`, for example).

Would a release with them in be plausible in the near future?

**Comment by SpaceManiac** [comment]
The current blocker is #54. The current implementation is close but not perfect. I want to get a release out but I want to get that done first, and I haven't had time lately to sit down and get it just right.

**Comment by SpaceManiac** [comment]
v0.7.0 out now.

**Comment by nabijaczleweli** [comment]
Very nice!
