### ISSUE TITLE
Parse timestamps using chrono crate

### ISSUE THREAD

**Issue by clarfonthey** [SpaceManiac/discord-rs#92]
Right now all of the timestamps are listed as strings, but it'd be nice if they were all parsed using the `chrono` crate so that they could be directly read and compared.

**Comment by Xaeroxe** [comment]
I'm actually already doing this in my bot, I'd be happy to make a PR if @SpaceManiac wants this feature.

**Comment by SpaceManiac** [comment]
Yes, I'm interested in making this change. Feel free to open a PR.

**Comment by Xaeroxe** [comment]
PR opened: https://github.com/SpaceManiac/discord-rs/pull/117

**Comment by iddm** [comment]
The pr is merged but the issue is still open. I think, it should be closed. @SpaceManiac
