### ISSUE TITLE
edit_embed

### ISSUE THREAD

**Issue by ArtemGr** [SpaceManiac/discord-rs#98]
Hey!

So I'm using `fn send_embed` to send some information to the users.

Later I want to *update* that information.

There is `fn edit_message`, but it only changes the text *before* the embed.  
Embed stays the same, it isn't even removed.

Please please please add `fn edit_embed` or by some other means allow the bots to update their embeds!

P.S. Do you have a Patreon page?

**Comment by SpaceManiac** [comment]
Hi! The needed functionality has been added.

I do not have a Patreon, I don't think the model is suitable for how sporadic and hard to measure updates to `discord-rs` are. If you appreciate my work, feel free to Paypal me at the email on my profile.

**Comment by ArtemGr** [comment]
Coolio!

> I don't think the model is suitable for how sporadic and hard to measure updates to discord-rs are.

I don't know, it feels good supporting something in the long term, like a badge, and it's less to spend upfront as well. Paypal's on the way.
